### PR TITLE
Allow Time() to return either T or void

### PR DESCRIPTION
**Pull request by mediocretes**
Includes #11!

Allows user to call Time() with an action that returns void (like () => { DoThings(); }) or an action that returns a value (like () => { return DoThings(); }).

### CODE REVIEW

**Comment by mediocretes** [comment]
The meat of this PR is in 524d011729c6eaef84da42394a039f003a493686

**Comment by jqr** [comment]
Inspect just the [changes specific to this branch](https://github.com/Instrumental/instrumental_agent-csharp/compare/wait_for_authentication...Instrumental:time_return_void).

**Comment by jqr** [comment]
Not including changes from #11, this looks 👍

**Comment by jqr** [comment]
Do we need a change to the `README.md` too?

**Comment by mediocretes** [comment]
I don't think so, the code in the README still works.  If someone needs to use a lambda that returns void rather than one that returns a value, they'll try it and be happy it works.  The documentation with the returnable version should be sufficient to demonstrate use, though.

**Comment by mediocretes** [comment]
Planning to merge this as soon as #11 gets merged.

**Pull request merged**
