### PR TITLE
Updated copyright.

### PR DESCRIPTION
**Pull request by jason-o-matic**

### CODE REVIEW

**Comment by janxious** [comment]
Is it your belief that we can't centralize the license to a file and remove all the individual file license entries? If yes, then :+1:

**Comment by esquivalient** [comment]
👍  Assuming we got permission to change the copyright

**Comment by mediocretes** [comment]
We do not have that permission.

**Comment by mediocretes** [comment]
More detail:  I sent 1 email about copyright transfer to bloomerang's general contact email address.  I will follow up at least one more time, and then with a phone call before I announce that effort abandoned.

**Comment by janxious** [comment]
Emphasis Mine:

> \4. Redistribution.
> 
> You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
> 
> You must give any other recipients of the Work or Derivative Works a copy of this License; and You must cause any modified files to carry prominent notices stating that You changed the files; and You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. **You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.**

**Comment by mediocretes** [comment]
I got licensed.

:+1:

**Pull request merged**
